language: node_js

node_js:
  - '8.9'

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - 'node_modules'
    - $HOME/.npm

script:
  - yarn build
  - yarn test
# jobs:
#   include:
#     - stage: install
#       script: yarn install
#     - stage: build
#       script: yarn build
#     - stage: test
#       script: yarn test

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true